baseurl = "https://www.ottlngr.de/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "green"
  showMenuItems = 5
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "ottlngr"
    subtitle = "Personal website and blog."
    keywords = ""
    copyright = "Philipp Ottolinger"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "ottlngr"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
